In [40]:
import pandas as pd
import numpy as np
import seaborn as sns

In [30]:
df = pd.read_csv('FCP_train.csv', delimiter=';')

In [31]:
df

,TICKET_NUMBER,COUPON_NUMBER,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,FLIGHT_DATE_LOCAL,TIME_DEPARTURE_LOCAL_TIME,FLIGHT_DISTANCE,FLIGHT_RANGE,MARKETING_CARRIER,OPERATIONAL_CARRIER,BOOKED_CLASS,BOOKED_CABIN,AIRCRAFT_TYPE,FARE_BASIS,VAB,UPGRADED_FLAG,UPGRADE_TYPE,UPGRADE_SALES_DATE
0,8604424865748057,2,WXA,OUO,2007-05-16,19:40:00,1344,SHORT-HAUL,2434615205489683,2434615205489683,O,Economy,738,OZSTDJ0,STANDARD,N,NaN,NaN
1,9018301813990125,1,OUO,RRS,2007-08-26,13:55:00,6942,LONG-HAUL,2434615205489683,2434615205489683,U,Economy,788,UKPRO10,BASIC,N,NaN,NaN
2,2822510487722780,2,OUO,HIX,2007-03-20,16:40:00,7521,LONG-HAUL,2434615205489683,2434615205489683,U,Economy,788,ULPRO11,BASIC,N,NaN,NaN
3,2549944156700091,1,DZN,OUO,2007-04-08,06:05:00,721,SHORT-HAUL,2434615205489683,2434615205489683,W,Economy,E75,WSTDK0,STANDARD,N,NaN,NaN
4,1190217539484680,2,LFF,NTH,2007-01-17,18:05:00,522,SHORT-HAUL,2434615205489683,2434615205489683,W,Economy,CRN,WCSERT/UD10,OTHER,N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9224582,1096632497884510,1,LPF,OUO,2007-02-05,19:30:00,523,SHORT-HAUL,2434615205489683,2434615205489683,V,Economy,DH4,V1STD0,STANDARD,N,NaN,NaN
9224583,3483070439818554,2,KHY,OUO,2007-08-04,17:55:00,1070,SHORT-HAUL,2434615205489683,2434615205489683,U,Economy,E75,USAVJ21,SAVER,N,NaN,NaN
9224584,9976288626337719,1,BUG,OUO,2007-06-02,07:00:00,753,SHORT-HAUL,2434615205489683,2434615205489683,K,Economy,DH4,K1FLX0,FLEX,N,NaN,NaN
9224585,4552896002136837,1,HLJ,OUO,2007-09-16,18:00:00,940,SHORT-HAUL,2434615205489683,2434615205489683,S,Economy,E75,SSAVJ14,SAVER,N,NaN,NaN
9224586,8440648241069803,1,OUO,GPJ,2007-05-16,16:50:00,1138,SHORT-HAUL,2434615205489683,2434615205489683,K,Economy,E95,K1STD9,STANDARD,N,NaN,NaN

In [20]:
stay_lenght_map = {-9999: None}
df["STAY_LENGTH_D"] = df["STAY_LENGTH_D"].replace(stay_lenght_map)

In [14]:
df.columns

Index(['BOOKING_ID', 'TICKET_NUMBER', 'ORIGINAL_TICKET_NUMBER',
       'FORM_OF_PAYMENT', 'CURRENCY', 'TOTAL_PRICE', 'TOTAL_PRICE_PLN',
       'PAX_GENDER', 'PAX_TYPE', 'CORPORATE_CONTRACT_FLG', 'LOYAL_CUSTOMER',
       'LOYAL_CUSTOMER_ID', 'LOYAL_CUSTOMER_DATE_OF_BIRTH',
       'LOYAL_CUSTOMER_REGISTERED_DATE'],
      dtype='object')

In [ ]:
bkg = ['BOOKING_WINDOW_D',
       'STAY_LENGTH_D', 'BOOKING_LONG_HOUL_FLAG', 'PAX_N', 'TRIP_TYPE']
fcp = ['BOOKED_CABIN', 'VAB', 'COUPON_NUMBER', 'FLIGHT_DISTANCE', 'TIME_DEPARTURE_LOCAL_TIME']

In [11]:
cols = ['FLIGHT_DISTANCE', 'COUPON_NUMBER', 'TIME_DEPARTURE_LOCAL_TIME',
       'TOTAL_PRICE_PLN', 'CORPORATE_CONTRACT_FLG', 'BOOKING_WINDOW_D',
       'STAY_LENGTH_D', 'BOOKING_LONG_HOUL_FLAG', 'PAX_N',
       'sale_to_flight_time', 'flight_len', 'if_additional_upgrade',
       'same_carrier', 'is_sus_payment', 'intinerary_len', 'is_sus_currency',
       'FLIGHT_RANGE_LONG-HAUL', 'BOOKED_CABIN_Economy',
       'BOOKED_CABIN_Premium', 'VAB_OTHER', 'VAB_SAVER', 'VAB_STANDARD',
       'TRIP_TYPE_ROUND TRIP']

count    2.795940e+06
mean     5.000232e+15
std      2.886950e+15
min      1.478791e+10
25%      2.500311e+15
50%      4.998693e+15
75%      7.503350e+15
max      9.999994e+15
Name: BOOKING_ID, dtype: float64
count        2795940
unique           365
top       2007-01-10
freq           15113
Name: SALES_DATE, dtype: object
count    2.795940e+06
mean     4.428978e+15
std      2.105992e+15
min      1.436723e+14
25%      2.460356e+15
50%      4.656330e+15
75%      5.703060e+15
max      9.831241e+15
Name: SALES_MARKET, dtype: float64
count     2795940
unique          6
top        AGENTS
freq      1906771
Name: SALES_CHANNEL, dtype: object
count        2795940
unique             3
top       ROUND TRIP
freq         1589782
Name: TRIP_TYPE, dtype: object
count    2.795823e+06
mean     3.518893e+01
std      4.785467e+01
min     -1.000000e+00
25%      6.000000e+00
50%      1.700000e+01
75%      4.300000e+01
max      3.650000e+02
Name: BOOKING_WINDOW_D, dtype: float64
count     1872129.0
unique        366.0
top             2.0
freq       272896.0
Name: STAY_LENGTH_D, dtype: float64
count     2795940
unique          2
top             N
freq      2346035
Name: BOOKING_LONG_HOUL_FLAG, dtype: object
count     2795940
unique          2
top             N
freq      2795502
Name: BOOKING_DOMESTIC_FLAG, dtype: object
count    2.795940e+06
mean     3.272262e+00
std      4.011986e+00
min      1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      4.000000e+00
max      3.150000e+02
Name: FLIGHT_COUPONS, dtype: float64
count    2.795940e+06
mean     1.653938e+00
std      5.077988e-01
min      1.000000e+00
25%      1.000000e+00
50%      2.000000e+00
75%      2.000000e+00
max      1.000000e+01
Name: SEGMENTS, dtype: float64
count    2.795940e+06
mean     1.398803e+00
std      1.476202e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      9.900000e+01
Name: PAX_N, dtype: float64
count         2795940
unique          55794
top       XMK-OUO-XMK
freq            29415
Name: INTINERARY, dtype: object
count     2795940
unique        145
top           OUO
freq       724283
Name: BOOKING_ORIGIN_AIRPORT, dtype: object
count     2795939
unique         51
top            PL
freq       975386
Name: BOOKING_ORIGIN_COUNTRY_CODE, dtype: object
count                 2795823
unique                  83698
top       2007-07-15 17:50:00
freq                      486
Name: BOOKING_DEPARTURE_TIME_UTC, dtype: object
count     2513483
unique        147
top           OUO
freq       534826
Name: BOOKING_DESTINATION_AIRPORT, dtype: object
count     2513483
unique         50
top            PL
freq       760848
Name: BOOKING_DESTINATION_COUNTRY_CODE, dtype: object
count                 2795940
unique                  86418
top       2007-06-07 19:40:00
freq                      601
Name: BOOKING_ARRIVAL_TIME_UTC, dtype: object
count     2795940
unique          2
top             N
freq      2790104
Name: UPGRADED_FLAG, dtype: object
count           5836
unique           478
top       2007-09-04
freq              36
Name: UPGRADE_SALES_DATE, dtype: object
count            5836
unique              6
top       lot upgrade
freq             2057
Name: UPGRADE_TYPE, dtype: object

In [ ]:
#wyrzuciÄ‡ TOTAL_PRICE_PLN <0 // powinno byc wieksze od 0
#BOOKING_WINDOW_D = -1? days between sales date and initial departure date // powinno byÄ‡ wieksze rÃ³wne od 0
#FLIGHT_DISTANCE == 0? tylko braÄ‡ pod uwagÄ™ wiÄ™ksze niÅ¼ 0